export const MARKETS = [
  {
    id: "XAUUSD",
    name: "Gold",
    yahoo: "GC=F",
    tv: "OANDA:XAUUSD",
    asset: "metal",
    pip: 0.1,
    digits: 2,
    tickLabel: "tuki",
  },
  {
    id: "XAGUSD",
    name: "Silver",
    yahoo: "SI=F",
    tv: "OANDA:XAGUSD",
    asset: "metal",
    pip: 0.01,
    digits: 3,
    tickLabel: "tuki",
  },
  {
    id: "EURUSD",
    name: "EUR/USD",
    yahoo: "EURUSD=X",
    tv: "FX:EURUSD",
    asset: "forex",
    pip: 0.0001,
    digits: 5,
    tickLabel: "pip",
  },
  {
    id: "GBPUSD",
    name: "GBP/USD",
    yahoo: "GBPUSD=X",
    tv: "FX:GBPUSD",
    asset: "forex",
    pip: 0.0001,
    digits: 5,
    tickLabel: "pip",
  },
  {
    id: "USDJPY",
    name: "USD/JPY",
    yahoo: "USDJPY=X",
    tv: "FX:USDJPY",
    asset: "forex",
    pip: 0.01,
    digits: 3,
    tickLabel: "pip",
  },
  {
    id: "USDCHF",
    name: "USD/CHF",
    yahoo: "USDCHF=X",
    tv: "FX:USDCHF",
    asset: "forex",
    pip: 0.0001,
    digits: 5,
    tickLabel: "pip",
  },
  {
    id: "AUDUSD",
    name: "AUD/USD",
    yahoo: "AUDUSD=X",
    tv: "FX:AUDUSD",
    asset: "forex",
    pip: 0.0001,
    digits: 5,
    tickLabel: "pip",
  },
  {
    id: "USDCAD",
    name: "USD/CAD",
    yahoo: "USDCAD=X",
    tv: "FX:USDCAD",
    asset: "forex",
    pip: 0.0001,
    digits: 5,
    tickLabel: "pip",
  },
  {
    id: "NZDUSD",
    name: "NZD/USD",
    yahoo: "NZDUSD=X",
    tv: "FX:NZDUSD",
    asset: "forex",
    pip: 0.0001,
    digits: 5,
    tickLabel: "pip",
  },
  {
    id: "US30",
    name: "Dow Jones",
    yahoo: "^DJI",
    tv: "TVC:DJI",
    asset: "index",
    pip: 1,
    digits: 2,
    tickLabel: "point",
  },
  {
    id: "NAS100",
    name: "Nasdaq 100",
    yahoo: "^NDX",
    tv: "TVC:NDX",
    asset: "index",
    pip: 1,
    digits: 2,
    tickLabel: "point",
  },
  {
    id: "SPX500",
    name: "S&P 500",
    yahoo: "^GSPC",
    tv: "TVC:SPX",
    asset: "index",
    pip: 1,
    digits: 2,
    tickLabel: "point",
  },
  {
    id: "USOIL",
    name: "Crude Oil",
    yahoo: "CL=F",
    tv: "TVC:USOIL",
    asset: "energy",
    pip: 0.01,
    digits: 2,
    tickLabel: "tick",
  },
  {
    id: "NATGAS",
    name: "Natural Gas",
    yahoo: "NG=F",
    tv: "NYMEX:NG1!",
    asset: "energy",
    pip: 0.001,
    digits: 3,
    tickLabel: "tick",
  },
  {
    id: "BTCUSD",
    name: "Bitcoin",
    yahoo: "BTC-USD",
    tv: "BINANCE:BTCUSDT",
    asset: "crypto",
    pip: 1,
    digits: 2,
    tickLabel: "USD",
  },
  {
    id: "ETHUSD",
    name: "Ethereum",
    yahoo: "ETH-USD",
    tv: "BINANCE:ETHUSDT",
    asset: "crypto",
    pip: 0.1,
    digits: 2,
    tickLabel: "USD",
  },
];

export const TIMEFRAMES = {
  "5m": { interval: "5m", range: "5d", label: "5 Minute", hold: "15 min - 2 hours", style: "Scalp" },
  "15m": { interval: "15m", range: "10d", label: "15 Minute", hold: "1 - 8 hours", style: "Intraday" },
  "1h": { interval: "60m", range: "1mo", label: "1 Hour", hold: "4 hours - 2 days", style: "Intraday / Short swing" },
  "4h": { interval: "1h", range: "3mo", label: "4 Hour", hold: "1 - 7 days", style: "Swing" },
  "1d": { interval: "1d", range: "1y", label: "Daily", hold: "3 - 21 days", style: "Position / Swing" },
};

export function getMarket(id) {
  return MARKETS.find((m) => m.id.toUpperCase() === String(id).toUpperCase());
}
